name: qadiroon_front_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  flutter_html: ^2.2.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
