
import 'package:flutter/material.dart';

class serviceProviderCreditsScreen extends StatelessWidget
{
  @override
  Widget build(BuildContext context)
  {
    return ListView
    (
      scrollDirection: Axis.vertical,
      children: 
      [
        Text
        (
          '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac dictum diam. Aenean nec lorem cursus, vulputate urna vitae, pellentesque arcu. Donec placerat augue tellus, varius ultricies magna imperdiet vitae. Nulla facilisi. Phasellus semper magna non ex euismod varius. Etiam tempus tempor iaculis. Fusce tortor metus, vehicula non sagittis sit amet, laoreet eget mi. Morbi et sagittis risus, nec lacinia risus. Sed at ipsum dolor. Etiam ut tincidunt leo, aliquet tempus est. Sed maximus ante et tempor rhoncus.

In sit amet metus nec velit convallis molestie vitae sed lorem. Proin felis lorem, laoreet eget enim sed, lacinia tempor velit. Vivamus rutrum et magna in rutrum. Vivamus placerat rhoncus nunc id malesuada. Sed risus nibh, cursus nec diam nec, faucibus rhoncus lectus. Morbi viverra, nisl eget luctus accumsan, leo enim pretium neque, ac varius sem libero mollis turpis. Nunc finibus nunc eget tortor condimentum, et tempus metus consequat.

Nullam tristique arcu quam, tincidunt dictum mi vehicula id. Curabitur vitae velit mattis eros suscipit suscipit. Duis scelerisque vitae nisl a ultrices. Donec viverra et turpis vel sodales. Phasellus facilisis ligula non neque pharetra suscipit. Nullam et eros id enim scelerisque facilisis non vel mauris. Nam eu magna vel mauris placerat placerat vitae ac augue. Proin lacinia purus et odio imperdiet pellentesque. Etiam placerat convallis orci eget gravida. Ut posuere elit nisl, feugiat hendrerit elit condimentum in.

Aliquam a finibus odio. Praesent scelerisque sodales felis id egestas. Nullam volutpat volutpat nisl sed varius. In ac lobortis lectus, vitae vehicula tellus. Aenean eu sollicitudin velit. Vestibulum augue ex, lobortis id lacus et, viverra dictum nisl. Aenean a eros ligula. Praesent placerat lectus sapien, eget porta purus lobortis ac. Vivamus scelerisque ornare ante ac molestie. Vestibulum pretium tempor molestie. Integer maximus justo vel justo ultrices sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec semper neque eget odio molestie luctus eu commodo mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam sollicitudin laoreet arcu sed vulputate. Aliquam molestie nunc est, quis maximus leo iaculis eu.

Nunc sed rhoncus lorem, eu ullamcorper augue. Phasellus at erat lacus. Fusce in tempor est. Nam mattis felis sem, eu eleifend est interdum eget. Phasellus rutrum, mauris a lobortis cursus, risus augue imperdiet nibh, id pharetra lectus nisi at velit. Quisque in interdum mi. Etiam vel urna at turpis condimentum sollicitudin in eget nulla. Morbi pharetra facilisis rhoncus. Quisque nibh eros, dignissim sit amet euismod tempus, dictum in nibh. Duis et ante non nibh congue porta. Praesent at sodales erat. Aenean arcu enim, convallis a luctus non, fringilla ut purus. Nam gravida tortor ut dui sagittis volutpat. Nulla rutrum, lorem at bibendum viverra, est massa fermentum risus, blandit iaculis ex magna finibus sem. Nulla vehicula neque eget porta tempus. Proin eget faucibus erat.

Nullam tortor tellus, tristique sed varius nec, sagittis non dolor. Vivamus ultrices tincidunt sem, a consectetur enim hendrerit aliquet. Donec fringilla odio in sapien pellentesque, at bibendum massa rhoncus. Praesent sit amet ante eu lacus ultricies dictum. Suspendisse accumsan, sapien in ullamcorper euismod, tortor massa fermentum metus, et imperdiet odio libero quis dui. Nam et nisi sagittis, dictum tortor eget, sollicitudin massa. In hac habitasse platea dictumst. Nullam cursus tortor nibh, et consectetur odio egestas vitae. Morbi mi nunc, consequat a congue vel, lacinia sit amet massa. Fusce lorem purus, efficitur id volutpat vel, laoreet vel metus. Duis ornare in quam ut placerat. Suspendisse accumsan at nunc sed dictum. Cras ac metus sed ipsum finibus pellentesque tincidunt eu massa.

Phasellus bibendum lacinia volutpat. Morbi imperdiet risus arcu. Donec dolor nunc, facilisis et tellus a, pharetra vestibulum velit. In aliquet nunc tristique, tincidunt enim vitae, euismod eros. Pellentesque venenatis pellentesque ante, vitae condimentum sapien dictum eu. Aenean in auctor quam. Quisque at sollicitudin felis.

Vivamus eu leo sapien. Nullam mollis, purus efficitur imperdiet molestie, massa ante tempor sapien, non dignissim libero lorem et massa. Phasellus nisl magna, elementum nec dui non, suscipit lobortis sapien. Aenean imperdiet ligula dui, et suscipit metus accumsan eget. Duis venenatis justo ut odio feugiat, semper malesuada quam molestie. Proin lorem felis, varius a leo sit amet, feugiat fringilla arcu. Cras pharetra eleifend ante id feugiat. Sed magna leo, imperdiet vitae sapien ut, sodales volutpat nisi. Quisque maximus ut lorem vitae luctus. Etiam cursus porta odio. Morbi non est in lacus scelerisque sollicitudin vel semper urna. Praesent volutpat gravida ligula ac porta. Duis vitae placerat leo.

In at fermentum lacus, quis volutpat odio. Aliquam enim nunc, convallis id leo nec, ullamcorper congue nulla. Nulla bibendum, lectus sollicitudin ultricies tempus, elit ex aliquet augue, fermentum elementum dui nunc et nisi. Praesent quis elit a lorem lacinia pulvinar. Vivamus venenatis nisl quis velit volutpat, ut laoreet odio accumsan. Ut id lacus tincidunt neque finibus pretium. In malesuada nec est quis scelerisque. Nullam suscipit tortor eu ex tristique, vel vestibulum eros gravida. Donec ullamcorper posuere felis id tempus. Etiam accumsan ante vitae nisi dignissim rhoncus. Morbi purus magna, tincidunt nec nisi sed, lobortis egestas felis. Curabitur ultricies ut neque a ornare. Morbi id lobortis nunc. Nullam imperdiet, massa id porttitor rutrum, risus lectus convallis ante, eget pulvinar elit odio non lorem. Praesent placerat, dolor id vehicula faucibus, arcu diam vestibulum ante, ac bibendum lacus diam in ex.

Phasellus commodo, risus vitae vulputate feugiat, ante velit blandit eros, vitae aliquam libero magna in magna. Morbi non tellus id quam mollis finibus id sit amet tortor. Mauris mattis odio quis risus vulputate accumsan. Cras non imperdiet ligula, non ultrices nisi. Nulla congue tempus nisi, eu vestibulum massa dictum sed. Donec vel risus eros. Mauris gravida odio ac fringilla efficitur. Quisque at nisl nec ante accumsan placerat quis non urna. Suspendisse et pulvinar ligula. Nam mattis sit amet augue et suscipit. Morbi eget elit vulputate, gravida est in, sagittis nisl. Suspendisse faucibus porta elit at dictum. Quisque sodales ligula bibendum mauris laoreet, eget interdum elit euismod. Nullam lectus sem, aliquet id commodo nec, feugiat nec sem. Vestibulum in mollis diam. Proin sit amet nunc cursus, feugiat massa in, maximus neque.

Vestibulum dignissim, ipsum sit amet gravida posuere, leo ante molestie tortor, in cursus velit ligula at tellus. Aliquam pretium lorem id porttitor tempor. Vivamus ac orci nec velit lobortis tempor vel a lorem. Vestibulum in lacinia tortor. Nulla consectetur orci ante, vitae ultrices libero varius eu. Proin non urna velit. Sed sollicitudin ante id dolor porta rhoncus. Nulla quis blandit mauris. Quisque orci mauris, efficitur sodales nisl sed, scelerisque vehicula mi. Aenean a velit dictum, sodales leo vel, ornare magna. Vestibulum semper, ante dapibus tempor laoreet, orci lorem varius massa, id imperdiet nisi neque nec lacus. Phasellus porta orci vel ultricies mattis. Praesent ac odio ornare, scelerisque libero ut, ullamcorper eros. Nam id nibh eget eros vehicula euismod quis sed enim. Aliquam erat volutpat. Sed gravida dolor et quam posuere, id gravida lacus finibus.

Integer lacinia ligula diam, quis dictum libero egestas sed. Duis et arcu dui. Suspendisse sollicitudin pharetra ex nec ullamcorper. Phasellus at justo eu enim commodo varius ut in justo. Aenean ornare vitae massa placerat hendrerit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam orci est, elementum in interdum ut, vulputate eget ligula. Fusce ac venenatis leo. Phasellus porttitor ligula at libero iaculis efficitur.

Mauris mattis felis et placerat mollis. Proin tempus odio in eros volutpat, id blandit metus elementum. Aliquam rhoncus interdum turpis eu mollis. In id mauris sed nulla dictum scelerisque. Ut at faucibus nisl. Aenean vehicula orci et congue fermentum. Nullam sollicitudin imperdiet justo, nec aliquam velit vehicula vitae.

Nam non justo molestie, egestas augue ut, sollicitudin libero. Fusce rutrum accumsan tempus. Mauris efficitur neque eget odio feugiat mattis. Aliquam eleifend dignissim lectus, in aliquet sapien egestas a. Sed quis viverra neque, at dapibus ipsum. Aliquam non venenatis velit. Praesent lobortis lacinia fermentum. Ut at dignissim lectus, sit amet bibendum libero. Nunc in gravida purus. Maecenas tincidunt luctus mauris a malesuada. Pellentesque auctor imperdiet volutpat.

In quis malesuada dui. Nullam vehicula justo eget tempus egestas. Phasellus quis blandit est, sed vulputate ante. Suspendisse ex justo, pretium et mi et, rhoncus ornare orci. Aenean placerat a libero in venenatis. Donec semper volutpat nisi nec fringilla. Curabitur quis viverra dolor. Cras vitae ultricies odio. Suspendisse a lorem nec felis ullamcorper faucibus. Quisque mattis ex in sapien congue, in posuere magna luctus. Nulla facilisi.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus gravida lacinia nibh vitae dictum. Suspendisse eu mauris in odio facilisis finibus. In ornare accumsan ante, non volutpat sem rutrum ut. Curabitur magna purus, laoreet sit amet aliquam eu, fringilla vitae neque. Cras vitae nulla at ex sollicitudin ultricies. Aliquam erat volutpat. Pellentesque tellus est, rhoncus nec venenatis nec, fringilla quis enim. Nulla ac diam aliquet, pulvinar orci sit amet, euismod velit. Nulla ultricies molestie metus vel varius. Duis interdum ante a velit viverra, in imperdiet nibh sodales.

Nunc vel gravida metus. Ut mi nulla, interdum in vestibulum non, convallis ut libero. Vestibulum ultricies velit sed feugiat laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Duis porta molestie ipsum, vel lobortis nisi vulputate vitae. Morbi dignissim finibus vulputate. Donec facilisis mauris ut scelerisque maximus. Morbi malesuada facilisis sem sed congue. Curabitur semper dui lectus, non lobortis velit vehicula ac.

Pellentesque non rutrum felis, sit amet rutrum odio. Phasellus vitae eros eu sem semper pharetra vitae et nibh. Aenean venenatis laoreet neque quis fringilla. Suspendisse tincidunt dapibus erat ac rhoncus. Mauris efficitur, leo vel varius congue, risus sapien accumsan diam, sed blandit dolor diam nec urna. Fusce non urna quis felis fringilla mollis. Nulla et tempus erat. Donec sit amet felis dignissim lacus malesuada sollicitudin. Sed sollicitudin, lectus at sagittis suscipit, est dui elementum ex, auctor placerat lectus justo sit amet risus. Integer ut ex tortor. Vestibulum quis odio in dolor semper condimentum et a eros. Duis nec lacinia augue, non venenatis dolor. Nunc felis purus, dictum ut urna eu, pellentesque posuere odio. Suspendisse vel erat ut lorem gravida pretium gravida id metus. Aenean iaculis mattis massa, in ultrices ligula auctor vel. Praesent venenatis, orci eu dictum sodales, sapien risus tristique ex, non consectetur quam dui quis ante.

Nullam nec dui at justo tincidunt bibendum in nec augue. Integer ullamcorper fermentum purus eget finibus. Donec quis rutrum lacus, quis dignissim elit. Mauris blandit sapien ac mauris congue rutrum. Fusce sollicitudin porttitor ligula, rhoncus congue erat aliquam eget. Sed elementum augue est, sed lobortis velit mattis a. Nullam imperdiet pellentesque imperdiet. Morbi ipsum tellus, consectetur vitae nulla et, euismod suscipit risus. Aliquam erat volutpat. Integer finibus quam nec feugiat egestas. Aliquam quis arcu ut tellus mollis finibus. Curabitur mi ipsum, ullamcorper ac aliquam sed, imperdiet vel nunc. Proin posuere magna quis metus rutrum sagittis. Maecenas ullamcorper, lacus vel maximus pretium, nibh enim ullamcorper tellus, vel hendrerit ex velit ac nunc.

Suspendisse elementum elit quis semper elementum. Praesent vel nunc gravida, semper nisi nec, dapibus mauris. Vestibulum tristique maximus nisl sit amet lacinia. Suspendisse vestibulum eros a mi aliquet commodo. Aliquam vel nulla elit. Etiam feugiat nulla sed tincidunt porta. Sed commodo tortor at arcu varius, sit amet fermentum nisi sodales. Duis consequat odio nec tellus feugiat, id efficitur tellus ultrices. Cras ipsum justo, fermentum vitae odio vitae, tincidunt mattis lorem.

Maecenas tincidunt lacus massa, vitae faucibus turpis sodales a. Aenean vulputate ultrices nibh sed commodo. Curabitur tincidunt nunc eget urna mattis euismod. Cras posuere hendrerit dui, vel dictum turpis ullamcorper quis. Maecenas eu ultricies ipsum. Phasellus consectetur nec orci sed volutpat. Integer nec nisl ut sem finibus porta. Sed tristique volutpat urna quis ornare. Mauris molestie, sapien at ullamcorper volutpat, quam massa ultrices lectus, ornare cursus nulla velit et nibh. Nulla sed neque dolor. Proin faucibus ligula sed leo iaculis, in dapibus justo mattis. Praesent scelerisque magna non massa gravida, sed consequat mauris finibus. Proin arcu leo, faucibus in odio sed, suscipit ultricies ex.

Nam aliquam pretium ipsum, aliquet venenatis nisi semper at. Donec eget elit egestas, pharetra diam eu, congue risus. Nulla congue lobortis leo sed pretium. Suspendisse et nulla vel elit facilisis rhoncus id nec mi. Ut laoreet urna justo, varius lacinia augue faucibus ut. Integer aliquam pretium feugiat. Integer efficitur vel est vel molestie. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec vehicula pulvinar egestas. Proin ultricies orci ut ultricies placerat. Nullam sed sollicitudin lorem. In sagittis bibendum eros vitae scelerisque. Nam tempus quam non eleifend vulputate. Mauris laoreet, justo ac varius tempor, nulla mauris congue augue, ut scelerisque purus velit id nulla. Nulla ac tellus malesuada eros tempor eleifend at in tellus. Pellentesque at orci eget erat porta pulvinar in ultricies diam.

Maecenas facilisis, tellus eu semper sollicitudin, leo tortor pretium arcu, molestie feugiat odio lorem dignissim velit. In ullamcorper pretium aliquam. Nunc rhoncus nibh vel libero lobortis, at facilisis dui bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec aliquet interdum purus, vestibulum tincidunt ante ultricies at. Nulla facilisi. Sed bibendum libero quam, sed congue purus condimentum nec. Integer ornare suscipit metus, eget finibus magna tincidunt at. Donec urna ante, sollicitudin et volutpat nec, dapibus id libero. Integer feugiat rutrum accumsan. Ut vitae interdum metus. Nullam mauris sem, ultrices eu enim eu, facilisis gravida ante. Nam tempus nisl non neque tincidunt, vitae scelerisque sapien condimentum.

Aliquam consectetur egestas feugiat. Mauris elementum augue at dolor suscipit, at mollis mi tincidunt. Morbi pellentesque bibendum rutrum. Morbi at semper augue. Vivamus a velit in mauris lacinia scelerisque ac sit amet lectus. Mauris luctus mi at tellus maximus, quis sollicitudin elit finibus. Fusce vestibulum eleifend magna at tristique. Nulla facilisi. In venenatis velit eget augue viverra tempus.

Ut laoreet ornare ipsum, sed convallis eros. Donec at egestas orci, a consequat lectus. Morbi molestie at risus eget fringilla. Curabitur diam lorem, pharetra dapibus viverra at, luctus in libero. Aliquam id placerat nisi. In sit amet mi pharetra, sollicitudin nisi ut, sagittis mauris. Maecenas euismod purus congue magna sollicitudin, in tincidunt mi dapibus. Proin dignissim rutrum quam eget mattis. Nulla aliquam at eros eget gravida. Pellentesque ornare quam et est aliquet suscipit. Aliquam erat volutpat. Praesent a tristique orci, fringilla fermentum mauris. Cras mi lorem, laoreet vitae ligula ornare, ullamcorper tincidunt mi. Vestibulum venenatis lacinia arcu. In porttitor, nibh quis ullamcorper ornare, nisi magna sollicitudin elit, non consectetur diam metus tristique enim.

Phasellus accumsan ipsum id lacus dignissim, nec congue felis pulvinar. Cras tristique tortor quam, at convallis orci gravida ut. Vivamus nec felis malesuada, tempor dolor vehicula, commodo dolor. Sed eleifend pharetra elementum. Quisque pellentesque turpis eu leo pellentesque, sit amet pulvinar enim mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer in nibh sapien. Nam neque mi, malesuada eu lectus vel, efficitur tincidunt purus. Sed ac quam efficitur, ultricies libero ut, cursus justo. Nam egestas neque et leo sodales, eget vehicula elit efficitur. Integer augue sem, tempor sed augue maximus, aliquam molestie dui.

Suspendisse vitae pharetra mi. Phasellus vel mi sit amet nisi congue rhoncus nec vestibulum risus. Ut a gravida tortor, ut sodales diam. Etiam imperdiet dolor tincidunt blandit posuere. Nulla laoreet mauris purus, quis lacinia massa finibus vel. Fusce non arcu congue, faucibus mi eget, pulvinar odio. Morbi diam nisi, sagittis in urna vitae, pretium tincidunt odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Praesent aliquet iaculis diam, in molestie ipsum. Etiam quis faucibus nibh. Donec id magna sit amet nibh ullamcorper lobortis. Curabitur dui nunc, rhoncus quis consectetur ac, luctus eu quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec quis nibh risus. Suspendisse dapibus malesuada odio ut feugiat. Morbi vel ligula non justo vulputate iaculis. Pellentesque rutrum ultrices elit, et aliquam turpis.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus aliquet convallis nulla in fringilla. Duis venenatis sollicitudin ex, eget suscipit nibh. Vivamus ac sollicitudin orci, at porttitor quam. Proin lorem ipsum, porttitor et tellus vitae, vestibulum ultricies lacus. Fusce a leo quis quam consequat lobortis sed et orci. Vestibulum commodo mi semper mattis tincidunt. Nunc quis augue tristique, bibendum lectus quis, ultricies magna. Sed scelerisque, eros in lacinia fringilla, purus neque aliquet ante, nec elementum est nibh sed dolor. Cras at felis dui. Ut tempus eleifend sodales.

Morbi at porttitor justo, vitae finibus purus. Sed luctus convallis orci in sodales. Aliquam luctus vitae turpis quis placerat. Vestibulum lacinia tellus felis, nec consequat enim condimentum vel. Vivamus iaculis pellentesque eros ac molestie. Proin tempor, odio sed euismod varius, nisi augue gravida eros, in aliquet eros magna ac ligula. Praesent mauris erat, consectetur id rhoncus vitae, viverra sit amet enim. Maecenas euismod enim magna, in luctus ipsum auctor ac. Quisque tempus ut diam sit amet sollicitudin. Quisque sed nulla iaculis, vestibulum metus quis, vestibulum ipsum. Aliquam porttitor tristique augue, vel imperdiet tellus cursus non. Nullam bibendum lacus dolor, a lacinia lorem egestas vel. Phasellus ullamcorper felis ac dolor accumsan, at tristique urna malesuada. Vestibulum pretium ligula et pulvinar gravida. Mauris euismod, tellus vitae ornare sodales, est lorem pulvinar sapien, vel rutrum felis ante nec purus. Donec varius risus libero, at bibendum risus imperdiet in. 
          '''
        )
      ],
    );
  }
  
}