// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_VXxnPjRgMPUqiAvd5u6lrDb6XCjHSRU',
    appId: '1:535590890295:web:6b31fea03003687bdf88b2',
    messagingSenderId: '535590890295',
    projectId: 'qadiroon-db',
    authDomain: 'qadiroon-db.firebaseapp.com',
    storageBucket: 'qadiroon-db.appspot.com',
    measurementId: 'G-WJLH1HNZ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHfd7Hyik2obLVfolKj9mvA-S1wz_BUc',
    appId: '1:535590890295:android:ca8f8c10aa8a51b8df88b2',
    messagingSenderId: '535590890295',
    projectId: 'qadiroon-db',
    storageBucket: 'qadiroon-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDET2e28Or9ZHl4iwwgfUlh1SH_eA_AlAQ',
    appId: '1:535590890295:ios:ddeeeb909aec9f3fdf88b2',
    messagingSenderId: '535590890295',
    projectId: 'qadiroon-db',
    storageBucket: 'qadiroon-db.appspot.com',
    iosBundleId: 'com.example.qadiroonFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDET2e28Or9ZHl4iwwgfUlh1SH_eA_AlAQ',
    appId: '1:535590890295:ios:ddeeeb909aec9f3fdf88b2',
    messagingSenderId: '535590890295',
    projectId: 'qadiroon-db',
    storageBucket: 'qadiroon-db.appspot.com',
    iosBundleId: 'com.example.qadiroonFrontEnd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_VXxnPjRgMPUqiAvd5u6lrDb6XCjHSRU',
    appId: '1:535590890295:web:2be9731fa602079fdf88b2',
    messagingSenderId: '535590890295',
    projectId: 'qadiroon-db',
    authDomain: 'qadiroon-db.firebaseapp.com',
    storageBucket: 'qadiroon-db.appspot.com',
    measurementId: 'G-VZ5GNTNXV7',
  );
}
